/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jj2000_j2k_util_NativeServices */

#ifndef _Included_jj2000_j2k_util_NativeServices
#define _Included_jj2000_j2k_util_NativeServices
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jj2000_j2k_util_NativeServices
 * Method:    setThreadConcurrencyN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jj2000_j2k_util_NativeServices_setThreadConcurrencyN
  (JNIEnv *, jclass, jint);

/*
 * Class:     jj2000_j2k_util_NativeServices
 * Method:    getThreadConcurrencyN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jj2000_j2k_util_NativeServices_getThreadConcurrencyN
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
